name: AutoTeleport
main: com.mcmiddleearth.autoteleport.AutoTeleportPlugin
version: 0.2.1
description: automated teleportation plugin
load: POSTWORLD
softdepend: [ProtocolLib]
softdepend: [Multiverse-Core]
commands:
    atp:
        description: manage auto teleport areas
        usage: invalid subcommand
permissions:
    autoteleport.*:
        description: Gives access to all auto teleport commands
        default: op
        children:
            autoteleport.user: true
    autoteleport.user:
        description: gives access to /atp command
        default: op
