name: AutoTeleport
main: com.mcmiddleearth.autoteleport.AutoTeleportPlugin
version: 0.1
description: automated teleportation plugin
load: POSTWORLD
softdepend: [Multiverse-Core]
commands:
    atele:
        description: manage MiniGames plugin
        usage: TBA
permissions:
    autoteleport.*:
        description: Gives access to all miniGames commands
        default: op
        children:
            autoteleport.staff: true
    autoteleport.staff:
        description: Gives access to /game delete command
        default: op
